### ISSUE TITLE
Revamp plotting/figures

### ISSUE THREAD

**Issue by teubert** [nasa/prog_models#129]
Consider redesign of plotting/figures for ease of use. 

## Tasks
 - [ ] Come up with design for updated figures
 - [ ] Get buy in on design
 - [ ] Implement, keeping backwards compatibility, as reasonable 
 - [ ] Document cases where backwards compatibility is lost
 - [ ] Add to release notes
 - [ ] Add to examples, tutorial
 - [ ] Add to documentation 
 - [ ] Add tests

## DoD
 - Updated plotting features
 - Updated examples, tutorial
 - Updated documentation 
 - Added to release notes

**Comment by teubert** [comment]
e.g., https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.line.html
